### PR TITLE
Cherry-picked backport fix for Issue #178 to v0.10-stable

### PR DESCRIPTION
**Pull request by dewhisna**
For people needing to remain on v0.10-stable (v0.10.3 at present), yet needing Apache2 mod_wsgi to work ( see Issue #178 ), I back ported pokoli's fixes for replacing BeautifulSoup with bleach, which works admirably:

pokoli@b8b8cacd751a3a2463fadb78780b41900d2f3034 : Replace BeautifulSoup with bleach to sanitanize html
pokoli@a1375b198106f98dd2153a1b1c338aabfd7302ea : Remove uneeded BeautifullSoup import

### CODE REVIEW

**Comment by dewhisna** [comment]
Hold up on merging this at least to the stable branch (though you may wish to create a similar "v0.10.3_with_bleach" branch to park it on).  I'm finding that it doesn't pass all of the test suite (and also does weird things with the 'p' tags in the editors), I'm currently working on first consolidating with your other two related merge commits FelixSchwarz@279d9d669715c6e23a7da65611b5e9fb554847af and FelixSchwarz@b263aa5beeecaccfa96b41049e15d5e780554adc and then looking to figure out why it's not functioning correctly.

So you may want to hold up merging this yet...  Though I'm curious if the current "master" branch is passing all of the tests or if it too has issues with html cleaning of the editor text?  I was having difficulties getting the HEAD from master to build correctly, which is why I backported these fixes to get my mod_wsgi installation to run since 0.10.3 was building for me.  But that was a couple days ago, so I'll try again...

**Comment by dewhisna** [comment]
OK.  I have it fixed now (I think).  I finished cherry-pick merging in the changes from  FelixSchwarz@279d9d669715c6e23a7da65611b5e9fb554847af and FelixSchwarz@b263aa5beeecaccfa96b41049e15d5e780554adc and I fixed some of the xhtml_normalization_test cases that had gotten dropped by people along the way, as it was missing the problem of clean_xhtml() p'ing all over the place (pun intended).  Implemented a fix for that problem that at least works for me.  Basically, it avoids adding the p-tags if the string is already bounded by p-tags.

You guys might want to pick up some of these changes for 'master' as well, since it seems to be a problem there also, unless you come up with a better solution.  At least this works for getting v0.10.3 up and going with mod_wsgi on Apache2 and so fixes it for me for the time being.

Cheers!

**Comment by FelixSchwarz** [comment]
Thank you very much for your efforts and spotting the "p wrapping" problem. Bonus points as you resurrected some unit tests which are sorely needed (as demonstrated by the regressions).

I think it's best if we fix the regressions found so far (#216 and #217) first and then we can backport the fixes pretty easily. Would you mind to submit the unit tests and potential fixes for master? Alternatively I could extract your changes from the commits referenced above (of course I'll make sure you get proper credits for that and make sure that you can approve them before I push them in the official repo).

**Comment by rbu** [comment]
It looks all these commits are already cherry-picked onto master and the issues are tracked independently.

So I'm going to close this issue, please reopen or let me know if you disagree.

**Pull request closed without merging**
