### PR TITLE
Replace BeautifulSoup with bleach to sanitanize html

### LINKED ISSUE #178: Beautifulsoup issue
Hi, 
I am trying to configure mediadrop on my ubuntu server.
When I try to run : paster serve --reload deployment.ini , it give me following error.

Starting subprocess with file monitor
Traceback (most recent call last):
  File "/usr/local/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 224, in loadobj
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 409, in get_context
    section)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 431, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 361, in get_context
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 285, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 561, in get_context
    object_type, name=name)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 587, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/var/www/MediaCore/mediacore/config/middleware.py", line 34, in <module>
    from mediacore.config.environment import load_environment
  File "/var/www/MediaCore/mediacore/config/environment.py", line 19, in <module>
    import mediacore.lib.helpers
  File "/var/www/MediaCore/mediacore/lib/helpers.py", line 29, in <module>
    from mediacore.lib.auth import viewable_media
  File "/var/www/MediaCore/mediacore/lib/auth/__init__.py", line 3, in <module>
    from mediacore.lib.auth.middleware import *
  File "/var/www/MediaCore/mediacore/lib/auth/middleware.py", line 20, in <module>
    from mediacore.lib.auth.permission_system import MediaCorePermissionSystem
  File "/var/www/MediaCore/mediacore/lib/auth/permission_system.py", line 15, in <module>
    from mediacore.model import DBSession, Group, User
  File "/var/www/MediaCore/mediacore/model/__init__.py", line 21, in <module>
    from mediacore.lib.xhtml.htmlsanitizer import entities_to_unicode
  File "/var/www/MediaCore/mediacore/lib/xhtml/__init__.py", line 16, in <module>
    from mediacore.lib.xhtml.htmlsanitizer import (Cleaner,
  File "/var/www/MediaCore/mediacore/lib/xhtml/htmlsanitizer.py", line 42, in <module>
    tree=treebuilders.getTreeBuilder("beautifulsoup"),
  File "/usr/local/lib/python2.7/dist-packages/html5lib/treebuilders/__init__.py", line 75, in getTreeBuilder
    raise ValueError("""Unrecognised treebuilder "%s" """ % treeType)
ValueError: Unrecognised treebuilder "beautifulsoup"

BTW, I am using python 2.7 on ubuntu 12.04
Please let me to fix this issue.

Thanks
Harpreet Gill

### PR DESCRIPTION
**Pull request by pokoli**
Fixes #178

### CODE REVIEW

**Comment by pokoli** [comment]
Added a new commit that replaces links with proper tags and ensured that all related tests where passing.

**Comment by canatella** [comment]
Still have some problems:

- the bleach package is not on the mediadrop.org pypi,
- the mediadrop/forms/__init__.py still import BeautifullSoup

But after fixing that it's working ok. Thanks.

**Comment by pokoli** [comment]
@canatella thans for your comments. I removed the BeautifullSoup missing import. 

I cant not add the bleach package on the mediadrop.org pypi, but it's available on pypi, so I think there is no need to do so.

**Comment by canatella** [comment]
So for people like me who don't know much about python deployments, to skip the mediadrop pypi for downloading the bleach package, in mediadrop-git/setup.cfg, comment out the allow_hosts line:

    [easy_install]
    # Look to our server for a known-good set of dependencies
    find_links = http://static.mediadrop.net/dependencies/dev/ 
    #allow_hosts = static.mediadrop.net

**Comment by mvalin** [comment]
Thank you, I test your fix merging with original git/mediadrop and everything seems to work.

Regards

**Comment by FelixSchwarz** [comment]
thank you very much for implementing this. Just one minor pick: I had to remove some more references to BeautifulSoup in b263aa5beeecaccfa96b41049e15d5e780554adc

**Comment by pokoli** [comment]
Thank you for merging it!

**Pull request merged**
